wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699454457.051497
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
dataset:
  desc: null
  value: lsvm
nbids:
  desc: null
  value: 20
bidder_id:
  desc: null
  value: 3
model:
  desc: null
  value: mvnn
train_percent:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
num_hidden_layers:
  desc: null
  value: 1
num_hidden_units:
  desc: null
  value: 20
layer_type:
  desc: null
  value: MVNNLayerReLUProjected
target_max:
  desc: null
  value: 1
lin_skip_connection:
  desc: null
  value: 1
dropout_prob:
  desc: null
  value: 0
